version: 2
orbs:
  node: circleci/node@4.7.0
jobs:
  bobby:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "check from first ever build"
  sally:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "check from second build"
workflows:
  version: 2
  bobby_sally: 
    jobs: 
      - bobby
      - sally
      
