version: 2
orbs:
  node: circleci/node@4.7.0
jobs:
  build:
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - run: echo "npm installing"
      - run: npm install
      - run: CI=true npm run build
  test:
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - run: echo "Testing job"
      - run: npm install
      - run: npm test
  hithere:
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - run: echo "Hi from hi there job" 
workflows:
  version: 2
  build_test_lint: 
    jobs: 
      - build
      - hithere
      - test:
          requires:
            - hithere
      
